<script lang="ts">
  import { workspace, data } from '$lib/api/endpoints';
  import { onMount } from 'svelte';
  import { Badge, Card, Separator } from '$lib/components/ui';

  let modules = $state<
    { slug: string; name: string; entities: number; entityNames: string[] }[]
  >([]);
  let totals = $state<Record<string, number>>({});
  let loading = $state(true);

  onMount(async () => {
    try {
      const bp = await workspace.blueprint();
      modules = bp.modules.map((m) => ({
        slug: m.slug,
        name: m.name,
        entities: m.entities.length,
        entityNames: m.entities.map((e) => e.name)
      }));
      await Promise.all(
        bp.modules.map(async (m) => {
          const e = m.entities[0];
          if (!e) return;
          try {
            const page = await data.list(m.slug, e.slug, { limit: 1 });
            totals[m.slug] = page.total;
          } catch {
            totals[m.slug] = 0;
          }
        })
      );
    } finally {
      loading = false;
    }
  });
</script>

<header class="mb-6 flex items-end justify-between">
  <div>
    <h1 class="text-xl font-semibold">Workspace</h1>
    <p class="text-sm text-muted-foreground">
      Modules generated by your prompts. Everything here was built at runtime.
    </p>
  </div>
  <a href="/app/build" data-testid="goto-build"
    class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-silver-dim">
    Build something
  </a>
</header>

{#if loading}
  <p class="text-sm text-muted-foreground">Loadingâ¦</p>
{:else if modules.length === 0}
  <Card class="p-8 text-center">
    <p class="text-sm text-muted-foreground">
      No modules yet. Use <a class="underline" href="/app/build">Build</a> and describe what you need.
    </p>
  </Card>
{:else}
  <div class="flex flex-col gap-3">
    {#each modules as m (m.slug)}
      <a href="/app/m/{m.slug}" data-testid="module-{m.slug}"
        class="flex items-center justify-between rounded-lg border border-border bg-surface px-4 py-3
               hover:bg-muted transition-colors">
        <div class="flex flex-col">
          <span class="font-medium">{m.name}</span>
          <span class="text-xs text-muted-foreground"
            >{m.entities} entities: {m.entityNames.join(', ')}</span
          >
        </div>
        <Badge variant="outline">{totals[m.slug] ?? 0} records</Badge>
      </a>
    {/each}
  </div>
{/if}
<Separator class="my-6" />
